import type { Metadata } from "next"
import { Noto_Sans } from "next/font/google"
import "./globals.css"
import AuthContext from "@/context/AuthContext"
import ToasterContext from "@/context/ToasterContext"

const notoSans = Noto_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} bg-muted`}>
        <AuthContext>
          <ToasterContext />
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
